[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
dynamic_padding = true
decorations = "None"
opacity = 0.9
blur = true
option_as_alt = "Both"

[font]
size = 16

[font.normal]
family = "Google Sans Mono"
style = "Regular"

[font.bold]
family = "Google Sans Mono"
style = "Bold"

[font.italic]
family = "Google Sans Mono"
style = "Italic"

[font.bold_italic]
family = "Google Sans Mono"
style = "Bold Italic"
